version: '3'

services:
  store:
    build:
      context: ./
      dockerfile: ./store/Dockerfile
    ports:
      - "8000:8000"
    command: ["./run.sh"]
    environment:
      PG_USER: postgres
      PG_PASSWORD: pass
      PG_HOST: db
      PG_DB: srore_db
    depends_on:
      - db
    networks:
      - communication
  db:
    image: postgres
    volumes:
      - ./scripts/create_data_pg.sh:/docker-entrypoint-initdb.d/create_data_pg.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_BASE: srore_db
    networks:
      - communication

networks:
  communication:
    driver: bridge