# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-09 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
            ],
        ),
    ]
